# This is a customised demo, more details at:
# https://docs.docker.com/ee/ucp/kubernetes/

---

# DEPLOYMENT RESOURCE OF APP ITSELF
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  # name of deployment resource and pods
  name: ${cluster_name_short}-example
  # namespace not req for helm
  namespace: ${namespace_public}
  # resource labels
  labels:
    app: ${cluster_name_short}-example
spec:
  # how many replicas in cluster
  replicas: 1
  selector:
    matchLabels:
      app: ${cluster_name_short}-example
  template:
    metadata:
      labels:
        app: ${cluster_name_short}-example
    spec:
      # spec of pods/containers here
      containers:
      - name: ${cluster_name_short}-example
        # docker image
        image: nginx:1.7.9
        ports:
          # exposed port and protocol of deployment/pod(s)
        - containerPort: 8443
          protocol: TCP

---

# SERVICE RESOURCE
kind: Service
apiVersion: v1
metadata:
  # name of service resource
  name: ${cluster_name_short}-example
  # namespace not req for helm
  namespace: ${namespace_public}
  # resource labels
  labels:
    app: ${cluster_name_short}-example
spec:
  ports:
      # port of service
    - port: 80
      # port of deployment/pod(s) behind service
      targetPort: 8443
  selector:
    app: ${cluster_name_short}-example

---

# INGRESS RESOURCE
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  # name of ingress resource
  name: ${cluster_name_short}-example
  # namespace not req for helm
  namespace: ${namespace_public}
  labels:
    app: ${cluster_name_short}-example
  annotations:
    # specified because we use an nginx ingress-controller
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # host and path are combined to effective full external dns path
  - host: ${url_public}.${dns_domain_public}
    http:
      paths:
      - path: /s/${cluster_name_short}-example
        backend:
          # serviceName is the matching service resource
          serviceName: ${cluster_name_short}-example
          servicePort: 80
  tls:
  - hosts:
      # specify the dns name the cert is valid for
    - ${url_public}.${dns_domain_public}
    # secret name of the secret resource containing matching cert
    secretName: default-ingress-cert