## This template defines the issuers for Cert Manager
## LetsEncrypt ACME is available as 2 possible providers; staging and prod
## Route53 is used for DNS validation, using a instance role (no creds here)
# More at: https://cert-manager.readthedocs.io/en/latest/reference/issuers.html
#     and: https://cert-manager.readthedocs.io/en/latest/reference/clusterissuers.html

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  # namespace: ${namespace_public} # specify no namespace for ClusterIssuer, only Issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${letsencrypt_email}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    dns01:

      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:

        - name: route53
          route53:
            region: ${aws_region}
            hostedZoneID: ${aws_r53_zone_id}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # namespace: ${namespace_public} # specify no namespace for ClusterIssuer, only Issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${letsencrypt_email}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # ACME DNS-01 provider configurations
    dns01:

      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:

        - name: route53
          route53:
            region: ${aws_region}
            hostedZoneID: ${aws_r53_zone_id}